{'explore_vintage': {'market': {'country': 'kr',
   'currency': {'code': 'USD',
    'name': 'US Dollars',
    'prefix': '$',
    'suffix': None}},
  'records_matched': 3173,
  'matches': [{'vintage': {'id': 11630423,
     'seo_name': 'dulong-reserve-saint-emilion-2013',ㅁ
     'name': 'Dulong Reserve Saint-Émilion 2013',
     'statistics': {'status': 'Normal',
      'ratings_count': 69,ㅁ
      'ratings_average': 3.3,ㅁ
      'labels_count': 1226,
      'wine_ratings_count': 628,
      'wine_ratings_average': 3.5,
      'wine_status': 'Normal'},
     'image': {'location': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pl_480x640.png',
      'variations': {'bottle_large': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pb_x960.png',ㅁ
       'bottle_medium': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pb_x600.png',
       'bottle_medium_square': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pb_600x600.png',
       'bottle_small': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pb_x300.png',
       'bottle_small_square': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pb_300x300.png',
       'label': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pl_480x640.png',
       'label_large': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pl_375x500.png',
       'label_medium': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pl_150x200.png',
       'label_medium_square': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pl_150x150.png',
       'label_small_square': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pl_80x80.png',
       'large': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pl_375x500.png',
       'medium': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pl_150x200.png',
       'medium_square': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pl_150x150.png',
       'small_square': '//images.vivino.com/thumbs/xcjkIWBgQ2ayExtEwKjm_g_pl_80x80.png'}},
     'wine': {'id': 1136315,
      'name': 'Reserve Saint-Émilion',
      'seo_name': 'reserve-saint-emilion',a
      'type_id': 1,
      'vintage_type': 0,
      'is_natural': False,
      'region': {'id': 436,
       'name': 'Saint-Émilion',
       'name_en': '',
       'seo_name': 'saint-emilion',
       'country': {'code': 'fr',
        'name': 'France',
        'native_name': 'France',
        'seo_name': 'france',
        'currency': {'code': 'EUR',
         'name': 'Euros',
         'prefix': '€',
         'suffix': None},
        'regions_count': 1304,
        'users_count': 5552423,
        'wines_count': 568341,
        'wineries_count': 67611,
        'most_used_grapes': [{'id': 14,
          'name': 'Pinot Noir',
          'seo_name': 'pinot-noir',
          'has_detailed_info': True,
          'wines_count': 572334},
         {'id': 5,
          'name': 'Chardonnay',
          'seo_name': 'chardonnay',
          'has_detailed_info': True,
          'wines_count': 604208},
         {'id': 10,
          'name': 'Merlot',
          'seo_name': 'merlot',
          'has_detailed_info': True,
          'wines_count': 566719}]},
       'class': {'typecast_map': {'background_image': {}, 'class': {}}},
       'background_image': {'location': '//images.vivino.com/regions/backgrounds/FfzIrdtQS1mdPyifcUFfGQ.jpg',
        'variations': {'large': '//thumbs.vivino.com/region_backgrounds/FfzIrdtQS1mdPyifcUFfGQ_1280x760.jpg',
         'medium': '//thumbs.vivino.com/region_backgrounds/FfzIrdtQS1mdPyifcUFfGQ_600x356.jpg'}}},
      'winery': {'id': 13657,
       'name': 'Dulong',
       'seo_name': 'dulong',
       'status': 0,
       'background_image': None},
      'taste': {'structure': {'acidity': 3.348242,
        'fizziness': None,
        'intensity': 4.3980494,
        'sweetness': 1.1950549,
        'tannin': 3.3200002,
        'user_structure_count': 9,
        'calculated_structure_count': 40},
       'flavor': [{'group': 'oak',
         'stats': {'count': 15, 'score': 1304},
         'primary_keywords': [{'id': 434, 'name': 'vanilla', 'count': 6},
          {'id': 292, 'name': 'oak', 'count': 5},
          {'id': 83, 'name': 'cedar', 'count': 2},
          {'id': 422, 'name': 'tobacco', 'count': 1}],
         'secondary_keywords': [{'id': 242, 'name': 'leather', 'count': 3},
          {'id': 105, 'name': 'cinnamon', 'count': 1}]},
        {'group': 'black_fruit',
         'stats': {'count': 11, 'score': 1800},
         'primary_keywords': [{'id': 470, 'name': 'cassis', 'count': 3},
          {'id': 52, 'name': 'blackcurrant', 'count': 3},
          {'id': 39, 'name': 'black fruit', 'count': 3},
          {'id': 49, 'name': 'blackberry', 'count': 3},
          {'id': 334, 'name': 'plum', 'count': 2},
          {'id': 55, 'name': 'blueberry', 'count': 2},
          {'id': 135, 'name': 'dark fruit', 'count': 2}]},
        {'group': 'spices',
         'stats': {'count': 11, 'score': 687},
         'primary_keywords': [{'id': 249, 'name': 'licorice', 'count': 4},
          {'id': 373, 'name': 'rosemary', 'count': 1},
          {'id': 320, 'name': 'pepper', 'count': 1},
          {'id': 105, 'name': 'cinnamon', 'count': 1}],
         'secondary_keywords': [{'id': 434, 'name': 'vanilla', 'count': 6}]},
        {'group': 'non_oak',
         'stats': {'count': 8, 'score': 175},
         'primary_keywords': [{'id': 417, 'name': 'toast', 'count': 1}],
         'secondary_keywords': [{'id': 434, 'name': 'vanilla', 'count': 6},
          {'id': 83, 'name': 'cedar', 'count': 2},
          {'id': 422, 'name': 'tobacco', 'count': 1},
          {'id': 105, 'name': 'cinnamon', 'count': 1}]},
        {'group': 'earth',
         'stats': {'count': 8, 'score': 701},
         'primary_keywords': [{'id': 242, 'name': 'leather', 'count': 3},
          {'id': 156, 'name': 'earthy', 'count': 2},
          {'id': 276, 'name': 'minerals', 'count': 1},
          {'id': 398, 'name': 'stone', 'count': 1}],
         'secondary_keywords': [{'id': 422, 'name': 'tobacco', 'count': 1}]},
        {'group': 'red_fruit',
         'stats': {'count': 8, 'score': 800},
         'primary_keywords': [{'id': 354, 'name': 'red fruit', 'count': 4},
          {'id': 93, 'name': 'cherry', 'count': 1},
          {'id': 353, 'name': 'red currant', 'count': 1},
          {'id': 348, 'name': 'raspberry', 'count': 1},
          {'id': 352, 'name': 'red cherry', 'count': 1}]},
        {'group': 'microbio',
         'stats': {'count': 2, 'score': 133},
         'primary_keywords': [{'id': 91, 'name': 'cheese', 'count': 1}],
         'secondary_keywords': [{'id': 417, 'name': 'toast', 'count': 1}]},
        {'group': 'tree_fruit',
         'stats': {'count': 1, 'score': 100},
         'primary_keywords': [{'id': 469, 'name': 'stone fruit', 'count': 1}]},
        {'group': 'dried_fruit',
         'stats': {'count': 1, 'score': 100},
         'primary_keywords': [{'id': 347, 'name': 'raisin', 'count': 1}]}]},
         --------------- 와인의테이스트안끝
      'statistics': {'status': 'Normal',
       'ratings_count': 628,
       'ratings_average': 3.5,
       'labels_count': 8934,
       'vintages_count': 31}, 
       ----------------------- 와인 안 statistics/와인안 스타일
      'style': {'id': 266,
       'seo_name': 'bordeaux-right-bank-saint-emilion',
       'regional_name': 'Bordeaux Right Bank',
       'varietal_name': 'Saint-Émilion',
       'name': 'Bordeaux Saint-Émilion',
       'image': None,
       'background_image': {'location': '//images.vivino.com/backgrounds/styles/JqMTW-DLSdK6KYE6rtaiiA.jpg',
        'variations': {'small': '//images.vivino.com/backgrounds/styles/thumbs/JqMTW-DLSdK6KYE6rtaiiA_932x810.jpg'}},
       'description': "Made predominantly from Merlot and Cabernet Franc, Saint-Émilion wines tend to have a rich, mouth-drying tannic structure, which is balanced by the more juicy characteristics of plum and black cherry fruit, along with chocolate and sweet spice, developing savory tobacco and cedar characteristics with age.\n\nThe best Saint-Émilion wines will exhibit a terrific mineral vein, the result of vines being planted on the region's limestone escarpment. Vines planted on sandy soils tend to produce grapes that make lighter styled wines.\n\nSituated on the right bank of Bordeaux, the region of Saint-Émilion can boast of producing the most diverse range of styles, partly due to differences in soil types, from gravel to limestone to sand, but also thanks to production variations and winemakers looking to make their mark.",
       'blurb': None,
       'interesting_facts': ['The village of Saint-Émilion is a UNESCO World Heritage Site.',
        'Saint-Émilion was the first Bordeaux region to export its wines.',
        "Saint-Émilion is Bordeaux's largest major wine-producing region.",
        'Unlike other classified regions within Bordeaux, Saint-Émilion updates its classification roughly every 10 years.',
        'In Saint-Émilion Cabernet Franc is referred to as Bouchet.'],
       'body': 4,
       'body_description': 'Full-bodied',
       'acidity': 2,0
       'acidity_description': 'Medium',
       'country': {'code': 'fr',
                    'name': 'France',
                    'native_name': 'France',
                    'seo_name': 'france',
                    'currency': {'code': 'EUR',
                    'name': 'Euros',
                    'prefix': '€',
                    'suffix': None},
                    'regions_count': 1304,
                    'users_count': 5552423,
                    'wines_count': 568341,
                    'wineries_count': 67611,
                    'most_used_grapes': [{'id': 14,
                    'name': 'Pinot Noir',
                    'seo_name': 'pinot-noir',
                    'has_detailed_info': True,
                    'wines_count': 572334},
                    {'id': 5,
                    'name': 'Chardonnay',
                    'seo_name': 'chardonnay',
                    'has_detailed_info': True,
                    'wines_count': 604208},
                    {'id': 10,
                    'name': 'Merlot',
                    'seo_name': 'merlot',
                    'has_detailed_info': True,
                    'wines_count': 566719}]},
       'wine_type_id': 1,
       'food': [{'id': 4,
                'name': 'Beef',
                'background_image': {'location': '//images.vivino.com/backgrounds/foods/4_beef.png',
                'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/4_beef_932x810.png'}},
                'seo_name': 'beef'},
                {'id': 8,
                'name': 'Lamb',
                'background_image': {'location': '//images.vivino.com/backgrounds/foods/8_lamb.png',
                'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/8_lamb_932x810.png'}},
                'seo_name': 'lamb'},
                {'id': 11,
                'name': 'Game (deer, venison)',
                'background_image': {'location': '//images.vivino.com/backgrounds/foods/11_venison.png',
                'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/11_venison_932x810.png'}},
                'seo_name': 'game'},
                {'id': 20,
                'name': 'Poultry',
                'background_image': {'location': '//images.vivino.com/backgrounds/foods/20_chicken.png',
                'variations': {'small': '//images.vivino.com/backgrounds/foods/thumbs/20_chicken_932x810.png'}},
                'seo_name': 'poultry'}],
       'grapes': [{'id': 2,
                    'name': 'Cabernet Sauvignon',
                    'seo_name': 'cabernet-sauvignon',
                    'has_detailed_info': True,
                    'wines_count': 801751},
                    {'id': 3,
                    'name': 'Cabernet Franc',
                    'seo_name': 'cabernet-franc',
                    'has_detailed_info': True,
                    'wines_count': 269578},
                    {'id': 9,
                    'name': 'Malbec',
                    'seo_name': 'malbec',
                    'has_detailed_info': True,
                    'wines_count': 219735},
                    {'id': 10,
                    'name': 'Merlot',
                    'seo_name': 'merlot',
                    'has_detailed_info': True,
                    'wines_count': 566719},
                    {'id': 42,
                    'name': 'Petit Verdot',
                    'seo_name': 'petit-verdot',
                    'has_detailed_info': True,
                    'wines_count': 82567},
                    {'id': 51,
                    'name': 'Carménère',
                    'seo_name': 'carmenere',
                    'has_detailed_info': True,
                    'wines_count': 50087}],
       'region': {'id': 383,
        'name': 'Bordeaux',
        'name_en': '',
        'seo_name': 'bordeaux',
        'country': {'code': 'fr',
         'name': 'France',
         'native_name': 'France',
         'seo_name': 'france',
         'currency': {'code': 'EUR',
          'name': 'Euros',
          'prefix': '€',
          'suffix': None},
         'regions_count': 1304,
         'users_count': 5552423,
         'wines_count': 568341,
         'wineries_count': 67611,
         'most_used_grapes': [{'id': 14,
           'name': 'Pinot Noir',
           'seo_name': 'pinot-noir',
           'has_detailed_info': True,
           'wines_count': 572334},
          {'id': 5,
           'name': 'Chardonnay',
           'seo_name': 'chardonnay',
           'has_detailed_info': True,
           'wines_count': 604208},
          {'id': 10,
           'name': 'Merlot',
           'seo_name': 'merlot',
           'has_detailed_info': True,
           'wines_count': 566719}]},
        'parent_id': None,
        'background_image': {'location': '//images.vivino.com/regions/backgrounds/3z0tiBnOSPaSk5LxoYKRYg.jpeg',
         'variations': {'large': '//thumbs.vivino.com/region_backgrounds/3z0tiBnOSPaSk5LxoYKRYg_1280x760.jpeg',
          'medium': '//thumbs.vivino.com/region_backgrounds/3z0tiBnOSPaSk5LxoYKRYg_600x356.jpeg'}},
        'statistics': {'wineries_count': 13306,
         'wines_count': 42722,
         'sub_regions_count': 12,
         'parent_regions_count': 0}}},

         -----와인안 스타일 끝
      'has_valid_ratings': True},
     'year': 2013,
     'grapes': None,
     'has_valid_ratings': True},
   ----빈티지 끝
   
    'price': {'id': 14829052,
     'amount': 0.0336154031460408,
     'discounted_from': None,
     'discount_percent': None,
     'type': 'ppc',
     'sku': '5268',
     'url': 'http://www.winebow.co.kr/shop/goods/goods_view.php?goodsno=5268&category=002',
     'visibility': 1,
     'bottle_type_id': 1,
     'currency': {'code': 'USD',
      'name': 'US Dollars',
      'prefix': '$',
      'suffix': None},
     'bottle_type': {'id': 1,
      'name': 'Bottle (0.75l)',
      'short_name': 'bottle',
      'short_name_plural': 'bottles',
      'volume_ml': 750}},
    'prices': [{'id': 14829052,
      'amount': 0.0336154031460408,
      'discounted_from': None,
      'discount_percent': None,
      'type': 'ppc',
      'sku': '5268',
      'url': 'http://www.winebow.co.kr/shop/goods/goods_view.php?goodsno=5268&category=002',
      'visibility': 1,
      'bottle_type_id': 1,
      'currency': {'code': 'USD',
       'name': 'US Dollars',
       'prefix': '$',
       'suffix': None},
      'bottle_type': {'id': 1,
       'name': 'Bottle (0.75l)',
       'short_name': 'bottle',
       'short_name_plural': 'bottles',
       'volume_ml': 750}}]},
​
